"""modify

Revision ID: 0a60b1b1dab4
Revises: 12c6606cec4a
Create Date: 2020-05-03 23:25:02.852818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a60b1b1dab4'
down_revision = '12c6606cec4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pwresources', 'group_id')
    op.add_column('routes', sa.Column('usergroup_id', sa.Integer(), nullable=True))
    op.drop_column('routes', 'group_id')
    op.add_column('user', sa.Column('service_endtime', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('service_starttime', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('thunderservice_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('usergroup_id', sa.Integer(), nullable=True))
    op.drop_column('user', 'membership')
    op.drop_column('user', 'usergroup')
    op.drop_column('user', 'membership_endtime')
    op.drop_column('user', 'membership_starttime')
    op.add_column('usergroup', sa.Column('thunderservice_id', sa.Integer(), nullable=True))
    op.drop_column('usergroup', 'which_service')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergroup', sa.Column('which_service', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('usergroup', 'thunderservice_id')
    op.add_column('user', sa.Column('membership_starttime', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('membership_endtime', mysql.DATETIME(), nullable=False))
    op.add_column('user', sa.Column('usergroup', mysql.VARCHAR(length=2), nullable=True))
    op.add_column('user', sa.Column('membership', mysql.VARCHAR(length=2), nullable=True))
    op.drop_column('user', 'usergroup_id')
    op.drop_column('user', 'thunderservice_id')
    op.drop_column('user', 'service_starttime')
    op.drop_column('user', 'service_endtime')
    op.add_column('routes', sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('routes', 'usergroup_id')
    op.add_column('pwresources', sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
