"""new

Revision ID: 0c0dca065a2c
Revises: 9e0e395917b7
Create Date: 2020-07-18 16:56:51.459155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c0dca065a2c'
down_revision = '9e0e395917b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('certificateExpTime', sa.BigInteger(), nullable=True))
    op.add_column('routes', sa.Column('lastCheckTime', sa.BigInteger(), nullable=True))
    op.add_column('usergroup', sa.Column('maxUserCapacity', sa.Integer(), nullable=True))
    op.drop_column('usergroup', 'maxcapacity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergroup', sa.Column('maxcapacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('usergroup', 'maxUserCapacity')
    op.drop_column('routes', 'lastCheckTime')
    op.drop_column('routes', 'certificateExpTime')
    # ### end Alembic commands ###
