"""first

Revision ID: 12c6606cec4a
Revises: 
Create Date: 2020-05-01 00:09:35.847878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12c6606cec4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pwresources', 'group_id',
               existing_type=mysql.INTEGER(display_width=10),
               nullable=True)
    op.alter_column('routes', 'domain',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('routes', 'ipaddress',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('routes', 'servernameCN',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('routes', 'servernameEN',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index('groupID', table_name='routes')
    op.alter_column('thunderservice', 'membershipEN',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_index('id', table_name='thunderservice')
    op.drop_column('thunderservice', 'price')
    op.add_column('user', sa.Column('token', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('usergroup', sa.String(length=2), nullable=True))
    op.alter_column('user', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'membership_endtime',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'userGroup')
    op.alter_column('usergroup', 'which_service',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usergroup', 'which_service',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.add_column('user', sa.Column('userGroup', mysql.VARCHAR(length=2), nullable=True))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'membership_endtime',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('user', 'usergroup')
    op.drop_column('user', 'token')
    op.add_column('thunderservice', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.create_index('id', 'thunderservice', ['id'], unique=True)
    op.alter_column('thunderservice', 'membershipEN',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.create_index('groupID', 'routes', ['group_id'], unique=False)
    op.alter_column('routes', 'servernameEN',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('routes', 'servernameCN',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('routes', 'ipaddress',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.alter_column('routes', 'domain',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('pwresources', 'group_id',
               existing_type=mysql.INTEGER(display_width=10),
               nullable=False)
    # ### end Alembic commands ###
