"""nnnew

Revision ID: 2611ce26267e
Revises: c74b2f702b61
Create Date: 2020-06-03 16:54:51.965857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2611ce26267e'
down_revision = 'c74b2f702b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_status', sa.String(length=10), nullable=False))
    op.add_column('user', sa.Column('email_verified', sa.String(length=10), nullable=False))
    op.add_column('user', sa.Column('last_login_datetime', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_ipaddress', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('register_datetime', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('register_source', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'register_source')
    op.drop_column('user', 'register_datetime')
    op.drop_column('user', 'last_login_ipaddress')
    op.drop_column('user', 'last_login_datetime')
    op.drop_column('user', 'email_verified')
    op.drop_column('user', 'account_status')
    # ### end Alembic commands ###
