"""orders

Revision ID: 276ff79ed610
Revises: 839020a2f1db
Create Date: 2020-07-12 11:30:34.076689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '276ff79ed610'
down_revision = '839020a2f1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('coupon', sa.String(length=20), nullable=True))
    op.alter_column('orders', 'paymentMethod',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('orders', 'paymentStatus',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('orders', 'thunderserviceStatus',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.add_column('thunderservice', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('thunderservice', sa.Column('onSalePrice', sa.Float(), nullable=True))
    op.add_column('thunderservice', sa.Column('promotion', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thunderservice', 'promotion')
    op.drop_column('thunderservice', 'onSalePrice')
    op.drop_column('thunderservice', 'duration')
    op.alter_column('orders', 'thunderserviceStatus',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('orders', 'paymentStatus',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('orders', 'paymentMethod',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_column('orders', 'coupon')
    # ### end Alembic commands ###
