"""rescue

Revision ID: 379307fd58d3
Revises: 4ebe3f1f0357
Create Date: 2020-08-13 18:18:06.237087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379307fd58d3'
down_revision = '4ebe3f1f0357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpuio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ipaddress', sa.String(length=15), nullable=True),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('mem', sa.Float(), nullable=True),
    sa.Column('addtime', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diskio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ipaddress', sa.String(length=15), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('write_count', sa.Integer(), nullable=True),
    sa.Column('read_bytes', sa.Integer(), nullable=True),
    sa.Column('write_bytes', sa.Integer(), nullable=True),
    sa.Column('read_time', sa.BigInteger(), nullable=True),
    sa.Column('write_time', sa.BigInteger(), nullable=True),
    sa.Column('addtime', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load_average',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ipaddress', sa.String(length=15), nullable=True),
    sa.Column('one', sa.Float(), nullable=True),
    sa.Column('five', sa.Float(), nullable=True),
    sa.Column('fifteen', sa.Float(), nullable=True),
    sa.Column('addtime', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ipaddress', sa.String(length=15), nullable=True),
    sa.Column('up', sa.Integer(), nullable=True),
    sa.Column('down', sa.Integer(), nullable=True),
    sa.Column('total_up', sa.Integer(), nullable=True),
    sa.Column('total_down', sa.Integer(), nullable=True),
    sa.Column('up_packets', sa.Integer(), nullable=True),
    sa.Column('down_packets', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onlineuseramount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ipaddress', sa.String(length=15), nullable=True),
    sa.Column('online_user_amount', sa.Integer(), nullable=True),
    sa.Column('server_local_time', sa.String(length=50), nullable=True),
    sa.Column('server_start_time', sa.String(length=50), nullable=True),
    sa.Column('addtime', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thunderservice_id', sa.Integer(), nullable=True),
    sa.Column('placeOrderTime', sa.BigInteger(), nullable=True),
    sa.Column('coupon', sa.String(length=20), nullable=True),
    sa.Column('paymentMethod', sa.String(length=20), nullable=True),
    sa.Column('paymentTime', sa.BigInteger(), nullable=True),
    sa.Column('paymentSN', sa.String(length=100), nullable=True),
    sa.Column('emailNotification', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('orderStatus', sa.String(length=20), nullable=True),
    sa.Column('thunderserviceStatus', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('ipaddress', sa.String(length=15), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('ipv6', sa.Boolean(), nullable=True),
    sa.Column('trojanVersion', sa.String(length=100), nullable=True),
    sa.Column('servernameEN', sa.String(length=100), nullable=True),
    sa.Column('servernameCN', sa.String(length=100), nullable=True),
    sa.Column('routeStartTime', sa.BigInteger(), nullable=True),
    sa.Column('routeExpTime', sa.BigInteger(), nullable=True),
    sa.Column('trafficLimit', sa.Integer(), nullable=True),
    sa.Column('trafficUsed', sa.Integer(), nullable=True),
    sa.Column('trafficStartAt', sa.BigInteger(), nullable=True),
    sa.Column('trafficResetDay', sa.BigInteger(), nullable=True),
    sa.Column('usergroup_id', sa.Integer(), nullable=True),
    sa.Column('lastCheckTime', sa.BigInteger(), nullable=True),
    sa.Column('certificateExpTime', sa.BigInteger(), nullable=True),
    sa.Column('availablePwd', sa.Integer(), nullable=True),
    sa.Column('routeLocalTime', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thunderservice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('membershipCN', sa.String(length=20), nullable=False),
    sa.Column('membershipEN', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('defaultClientAmount', sa.Integer(), nullable=True),
    sa.Column('defaultTrafficAmount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('onSalePrice', sa.Float(), nullable=True),
    sa.Column('promotion', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logtime', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('result', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('remote_ip', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usergroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('maxUserCapacity', sa.Integer(), nullable=True),
    sa.Column('maxPwdCapacity', sa.Integer(), nullable=True),
    sa.Column('current_used', sa.Integer(), nullable=True),
    sa.Column('which_thunderservice', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pwresources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oripassword', sa.String(length=56), nullable=True),
    sa.Column('hashedpassword', sa.String(length=56), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('usergroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usergroup_id'], ['usergroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pwresources')
    op.drop_table('usergroup')
    op.drop_table('tracking')
    op.drop_table('thunderservice')
    op.drop_table('setting')
    op.drop_table('routes')
    op.drop_table('orders')
    op.drop_table('onlineuseramount')
    op.drop_table('network')
    op.drop_table('load_average')
    op.drop_table('diskio')
    op.drop_table('cpuio')
    # ### end Alembic commands ###
