"""new

Revision ID: 4b475eec4144
Revises: b8b1cba09678
Create Date: 2020-07-19 23:36:58.851703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b475eec4144'
down_revision = 'b8b1cba09678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routesDynamicData', sa.Column('availablePws', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routesDynamicData', 'availablePws')
    # ### end Alembic commands ###
