"""new111

Revision ID: 4ebe3f1f0357
Revises: da4e8b5edc1b
Create Date: 2020-08-13 17:16:16.577878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ebe3f1f0357'
down_revision = 'da4e8b5edc1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pwresources')
    op.drop_table('routes')
    op.drop_table('usergroup')
    op.drop_table('thunderservice')
    op.drop_table('tracking')
    op.drop_table('cpuio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpuio',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ipaddress', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('cpu', mysql.FLOAT(precision=11, scale=2), nullable=True),
    sa.Column('mem', mysql.FLOAT(precision=11, scale=2), nullable=True),
    sa.Column('addtime', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tracking',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('logtime', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('result', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('remote_ip', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('thunderservice',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('membershipCN', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('membershipEN', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('defaultClientAmount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('defaultTrafficAmount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('onSalePrice', mysql.FLOAT(), nullable=True),
    sa.Column('promotion', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('usergroup',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('group_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('current_used', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('which_thunderservice', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('maxPwdCapacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('maxUserCapacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('routes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sequence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('online', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('domain', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ipaddress', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('port', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('servernameEN', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('servernameCN', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('routeStartTime', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('routeExpTime', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('trafficLimit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('trafficUsed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('trafficStartAt', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('trafficResetDay', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('usergroup_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ipv6', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('trojanVersion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('certificateExpTime', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('lastCheckTime', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('availablePwd', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('routeLocalTime', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('pwresources',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('oripassword', mysql.VARCHAR(length=56), nullable=True),
    sa.Column('hashedpassword', mysql.VARCHAR(length=56), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('usergroup_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
