"""new

Revision ID: 58e6027c9126
Revises: 6ff24b9f14ca
Create Date: 2020-06-10 09:59:05.182872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58e6027c9126'
down_revision = '6ff24b9f14ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'account_status',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'email_verified',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'last_login_ipaddress',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'register_source',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'service_endtime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'service_endtime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'register_source',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'last_login_ipaddress',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'email_verified',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user', 'account_status',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
