"""new

Revision ID: 63d8f8e9e69c
Revises: 906f958b12bd
Create Date: 2020-08-26 21:32:46.313251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d8f8e9e69c'
down_revision = '906f958b12bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('yearly', sa.String(length=20), nullable=True),
    sa.Column('monthly', sa.String(length=20), nullable=True),
    sa.Column('daily', sa.String(length=20), nullable=True),
    sa.Column('hourly', sa.String(length=20), nullable=True),
    sa.Column('minutely', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('parameter1', sa.String(length=50), nullable=True),
    sa.Column('parameter2', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('k')
    # ### end Alembic commands ###
