"""modify

Revision ID: 6caa4d8275e0
Revises: 5be5c771922c
Create Date: 2020-05-03 23:30:32.872700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6caa4d8275e0'
down_revision = '5be5c771922c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pwresources', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('pwresources', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pwresources', sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('pwresources', 'user_id')
    # ### end Alembic commands ###
