"""new

Revision ID: 6ff24b9f14ca
Revises: 2611ce26267e
Create Date: 2020-06-08 22:54:46.129994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff24b9f14ca'
down_revision = '2611ce26267e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('affiliate', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('individual_coupon', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('mentor', sa.Integer(), nullable=True))
    op.drop_constraint('user_ibfk_2', 'user', type_='foreignkey')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_ibfk_1', 'user', 'usergroup', ['usergroup_id'], ['id'])
    op.create_foreign_key('user_ibfk_2', 'user', 'thunderservice', ['thunderservice_id'], ['id'])
    op.drop_column('user', 'mentor')
    op.drop_column('user', 'individual_coupon')
    op.drop_column('user', 'affiliate')
    # ### end Alembic commands ###
