"""orders

Revision ID: 839020a2f1db
Revises: 0c1502e5ff59
Create Date: 2020-07-11 13:23:32.146431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839020a2f1db'
down_revision = '0c1502e5ff59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thunderservice_id', sa.Integer(), nullable=True),
    sa.Column('placeOrderTime', sa.BigInteger(), nullable=True),
    sa.Column('paymentMethod', sa.String(length=20), nullable=False),
    sa.Column('paymentTime', sa.BigInteger(), nullable=True),
    sa.Column('paymentSN', sa.String(length=100), nullable=True),
    sa.Column('emailNotification', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('paymentStatus', sa.String(length=20), nullable=False),
    sa.Column('thunderserviceStatus', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
