"""new

Revision ID: 906f958b12bd
Revises: ac305620a28a
Create Date: 2020-08-16 21:33:11.829191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906f958b12bd'
down_revision = 'ac305620a28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('additional', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'additional')
    # ### end Alembic commands ###
