"""new

Revision ID: ac305620a28a
Revises: 379307fd58d3
Create Date: 2020-08-16 17:34:37.303912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac305620a28a'
down_revision = '379307fd58d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'status')
    # ### end Alembic commands ###
