"""sdfsad

Revision ID: c077507f399e
Revises: 883e0ccdc724
Create Date: 2020-06-20 19:07:02.418721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c077507f399e'
down_revision = '883e0ccdc724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('register_source', sa.String(length=50), nullable=True),
    sa.Column('register_datetime', sa.Integer(), nullable=True),
    sa.Column('service_starttime', sa.Integer(), nullable=True),
    sa.Column('service_endtime', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('usergroup_id', sa.Integer(), nullable=True),
    sa.Column('thunderservice_id', sa.Integer(), nullable=True),
    sa.Column('last_login_datetime', sa.Integer(), nullable=True),
    sa.Column('last_login_ipaddress', sa.String(length=50), nullable=True),
    sa.Column('mentor', sa.Integer(), nullable=True),
    sa.Column('individual_coupon', sa.String(length=50), nullable=True),
    sa.Column('affiliate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_index('email', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('account_status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('register_source', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('register_datetime', mysql.FLOAT(), nullable=True),
    sa.Column('service_starttime', mysql.FLOAT(), nullable=True),
    sa.Column('service_endtime', mysql.FLOAT(), nullable=True),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('usergroup_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('thunderservice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('last_login_datetime', mysql.FLOAT(), nullable=True),
    sa.Column('last_login_ipaddress', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mentor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('individual_coupon', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('affiliate', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_table('users')
    # ### end Alembic commands ###
