"""refreshtoken

Revision ID: c1a919af5094
Revises: c077507f399e
Create Date: 2020-06-22 11:42:48.435627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a919af5094'
down_revision = 'c077507f399e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refreshToken', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refreshToken')
    # ### end Alembic commands ###
